site_name: BIA Tournefeuille
site_description: 'Support de cours pour la préparation du BIA au lycée Françoise de Tournefeuille.'
site_author: 'Martial Pohin'
site_url: https://martialpohin.github.com/bia

repo_name: 'bia'
repo_url: 'https://github.com/martialpohin/bia'

google_analytics: 
  - 'UA-129882552-1' 
  - auto

nav:
  - Accueil: index.md
  - Sessions :
    - General: sessions/general.md
    - Session 1: sessions/1.md
    - Session 2: sessions/2.md
    - Session 3: sessions/3.md
    - Session 4: sessions/4.md
  - Themes:
    - Connaissance de l'avion: themes/aeronef.md
    - Aérodynamique: themes/aero.md
    - Météorologie: themes/meteo.md
    - Navigation et réglementation: themes/navigation.md
    - Histoire: themes/histoire.md
  - Ressources:
    - Livres de cours BIA: ressources/bia.md
    - Autres ressources BIA: ressources/other_bia.md
    - Culture aéronautique:
      - Aéronef: ressources/aeronef.md
      - Aérodynamique : ressources/aero.md
      - Météorologie: ressources/meteo.md
      - Navigation: ressources/navigation.md
      - Histoire: ressources/histoire.md
  - A propos: 
    - Contact: contact.md
    - Making-off: howto.md
theme: 
  name: material
  custom_dir: theme
use_directory_urls: false
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.details
