site_name: BIA Tournefeuille
site_description: 'Support de cours pour la préparation du BIA au lycée Françoise de Tournefeuille.'
site_author: 'Martial Pohin'
site_url: https://martialpohin.github.com/bia

repo_name: 'bia'
repo_url: https://github.com/martialpohin/bia

google_analytics: 
  - 'UA-169372827-1' 
  - auto

nav:
  - Accueil: index.md
  - Cours :
    - Progression : themes/progression.md
    - Connaissance de l'avion: themes/aeronef.md
    - Aérodynamique: themes/aero.md
    - Navigation et réglementation: themes/navigation.md
    - Météorologie: themes/meteo.md
    - Histoire: themes/histoire.md
    - Anglais: themes/anglais.md
  - Ressources:
    - Livres de cours BIA: ressources/bia.md
    - Autres ressources BIA: ressources/other_bia.md
  - Culture aéronautique:
      - BDthèque : ressources/bd.md
      - Histoire: ressources/histoire.md
      - Aéronef: ressources/aeronef.md
      - Aérodynamique : ressources/aero.md
      - Météorologie: ressources/meteo.md
      - Navigation: ressources/navigation.md
  - A propos: 
    - Contact: contact.md
    - Making-off: howto.md
theme: 
  name: material
  custom_dir: theme
use_directory_urls: false
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.details
